import { Lead, Profile, Organization, LeadDiscussion, LeadActivity } from '@/types/database';

export const mockOrganization: Organization = {
  id: 'org-venue',
  name: 'Star Celebration - A Royal Banquet Hall',
  slug: 'star-celebration',
  phone: '+91 72600 71154',
  email: 'starcelebration.patna@gmail.com',
  address: 'Bailey Road, Saguna More',
  city: 'Patna, Bihar',
  logo_url: '/logo.png',
  currency: 'INR',
  settings: {
    lead_sources: ['Meta', 'WhatsApp', 'Instagram', 'Facebook', 'Website', 'Google', 'Referral', 'Walk-in'],
    event_types: ['Wedding', 'Reception', 'Birthday', 'Ring Ceremony', 'Anniversary', 'Corporate', 'Party'],
  },
  created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
  updated_at: new Date().toISOString(),
};

export const mockProfiles: Profile[] = [
  {
    id: 'user-akash',
    organization_id: 'org-venue',
    name: 'Akash Sah',
    full_name: 'Akash Sah',
    email: 'starcelebration.patna@gmail.com',
    phone: '+91 72600 71154',
    role: 'owner',
    active: true,
    is_active: true,
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-rahul',
    organization_id: 'org-venue',
    name: 'Rahul Verma',
    email: 'rahul@grandimperial.com',
    phone: '+91 98765 22222',
    role: 'sales',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    active: true,
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-priya',
    organization_id: 'org-venue',
    name: 'Priya Singh',
    email: 'priya@grandimperial.com',
    phone: '+91 98765 33333',
    role: 'manager',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    active: true,
    created_at: new Date(Date.now() - 75 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-vikram',
    organization_id: 'org-venue',
    name: 'Vikram Malhotra',
    email: 'vikram@grandimperial.com',
    phone: '+91 98765 44444',
    role: 'sales',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    active: true,
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-neha',
    organization_id: 'org-venue',
    name: 'Neha Kapoor',
    email: 'neha@grandimperial.com',
    phone: '+91 98765 55555',
    role: 'front_desk',
    avatar_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=120&auto=format&fit=crop&q=80',
    active: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Reference timestamps for realistic follow-ups relative to right now
const now = Date.now();
const today5PM = new Date();
today5PM.setHours(17, 30, 0, 0);

const today6PM = new Date();
today6PM.setHours(18, 0, 0, 0);

const overdue2Days = new Date(now - 2 * 86400000);
overdue2Days.setHours(14, 0, 0, 0);

const overdue1Day = new Date(now - 1 * 86400000);
overdue1Day.setHours(16, 0, 0, 0);

const tomorrow11AM = new Date(now + 1 * 86400000);
tomorrow11AM.setHours(11, 0, 0, 0);

const in3Days = new Date(now + 3 * 86400000);
in3Days.setHours(15, 30, 0, 0);

export const mockDiscussions: Record<string, LeadDiscussion[]> = {
  'lead-1': [
    {
      id: 'disc-1-1',
      organization_id: 'org-venue',
      lead_id: 'lead-1',
      author_id: 'user-akash',
      body: 'Shared pricing catalog and premium stage decor options via WhatsApp. Customer is discussing the date with family elders and requested a callback today evening.',
      created_at: new Date(now - 24 * 3600000).toISOString(),
      updated_at: new Date(now - 24 * 3600000).toISOString(),
      author: mockProfiles[0],
    },
    {
      id: 'disc-1-2',
      organization_id: 'org-venue',
      lead_id: 'lead-1',
      author_id: 'user-rahul',
      body: 'Customer wants a 300 to 450-person reception in November. Asked for package pricing, veg+non-veg buffet menu combinations, and Imperial Hall photos with floral mandate.',
      created_at: new Date(now - 48 * 3600000).toISOString(),
      updated_at: new Date(now - 48 * 3600000).toISOString(),
      author: mockProfiles[1],
    },
  ],
  'lead-2': [
    {
      id: 'disc-2-1',
      organization_id: 'org-venue',
      lead_id: 'lead-2',
      author_id: 'user-priya',
      body: 'Spoke with Mr. Singhania. Looking for an intimate Ring Ceremony + Cocktail setup for 200 guests. Requested a special live pasta counter and customized DJ setup.',
      created_at: new Date(now - 3 * 86400000).toISOString(),
      updated_at: new Date(now - 3 * 86400000).toISOString(),
      author: mockProfiles[2],
    },
  ],
  'lead-4': [
    {
      id: 'disc-4-1',
      organization_id: 'org-venue',
      lead_id: 'lead-4',
      author_id: 'user-akash',
      body: 'Sent corporate banquet proposal with AV equipment, high-speed WiFi, and 3-course dinner layout for 600 delegates. Follow-up scheduled with their HR & Admin director.',
      created_at: new Date(now - 6 * 3600000).toISOString(),
      updated_at: new Date(now - 6 * 3600000).toISOString(),
      author: mockProfiles[0],
    },
  ],
  'lead-5': [
    {
      id: 'disc-5-1',
      organization_id: 'org-venue',
      lead_id: 'lead-5',
      author_id: 'user-rahul',
      body: 'Booking confirmed! ₹3,00,000 advance received. Grand Imperial Ballroom locked for 10th Feb 2027 Wedding (500 pax). Transitioned lead to Converted.',
      created_at: new Date(now - 12 * 86400000).toISOString(),
      updated_at: new Date(now - 12 * 86400000).toISOString(),
      author: mockProfiles[1],
    },
  ],
  'lead-7': [
    {
      id: 'disc-7-1',
      organization_id: 'org-venue',
      lead_id: 'lead-7',
      author_id: 'user-rahul',
      body: 'Visited hall on Sunday with bride and groom. They loved the outdoor lawn combination with the main ballroom. Discussion on corkage policy pending.',
      created_at: new Date(now - 18 * 3600000).toISOString(),
      updated_at: new Date(now - 18 * 3600000).toISOString(),
      author: mockProfiles[1],
    },
  ],
};

export const mockActivity: Record<string, LeadActivity[]> = {
  'lead-1': [
    {
      id: 'act-1-1',
      organization_id: 'org-venue',
      lead_id: 'lead-1',
      actor_id: 'user-akash',
      action_type: 'follow_up_updated',
      metadata: { details: 'Follow-up rescheduled to Today, 5:30 PM' },
      created_at: new Date(now - 24 * 3600000).toISOString(),
      actor: mockProfiles[0],
    },
    {
      id: 'act-1-2',
      organization_id: 'org-venue',
      lead_id: 'lead-1',
      actor_id: 'user-akash',
      action_type: 'discussion_added',
      metadata: { details: 'Shared pricing catalog and premium stage decor options' },
      created_at: new Date(now - 24 * 3600000).toISOString(),
      actor: mockProfiles[0],
    },
    {
      id: 'act-1-3',
      organization_id: 'org-venue',
      lead_id: 'lead-1',
      actor_id: 'user-priya',
      action_type: 'assigned',
      metadata: { details: 'Assigned to Rahul Verma' },
      created_at: new Date(now - 47 * 3600000).toISOString(),
      actor: mockProfiles[2],
    },
    {
      id: 'act-1-4',
      organization_id: 'org-venue',
      lead_id: 'lead-1',
      actor_id: 'user-rahul',
      action_type: 'lead_created',
      metadata: { details: 'Lead created via Meta Ads inquiry' },
      created_at: new Date(now - 48 * 3600000).toISOString(),
      actor: mockProfiles[1],
    },
  ],
};

export const mockLeads: Lead[] = [
  {
    id: 'lead-1',
    organization_id: 'org-venue',
    customer_name: 'Amit & Neha Kapur',
    phone: '9810123456',
    email: 'amit.kapur@gmail.com',
    source: 'Meta',
    event_type: 'Reception',
    event_date_status: 'fixed',
    event_date: '2026-11-22',
    guest_count_status: 'fixed',
    guest_count: 450,
    budget: 1250000,
    requirement: 'Grand reception dinner with both indoor ballroom and open-air poolside cocktail lounge.',
    owner_id: 'user-rahul',
    status: 'Interested',
    priority: 'High',
    next_follow_up_at: today5PM.toISOString(),
    follow_up_note: 'Call back to finalize menu tasting date and discuss family approval on pricing.',
    archived_at: null,
    created_at: new Date(now - 48 * 3600000).toISOString(),
    updated_at: new Date(now - 24 * 3600000).toISOString(),
    owner: mockProfiles[1],
    discussions: mockDiscussions['lead-1'],
    activity: mockActivity['lead-1'],
  },
  {
    id: 'lead-2',
      organization_id: 'org-venue',
    customer_name: 'Rajesh Singhania',
    phone: '9820098765',
    email: 'rsinghania@industrialgrp.com',
    source: 'WhatsApp',
    event_type: 'Ring Ceremony',
    event_date_status: 'fixed',
    event_date: '2026-12-05',
    guest_count_status: 'fixed',
    guest_count: 200,
    budget: 650000,
    requirement: 'Ring ceremony with floral theme and premium live food counters. Seeking package discount.',
    owner_id: 'user-priya',
    status: 'Follow-up',
    priority: 'High',
    next_follow_up_at: overdue2Days.toISOString(),
    follow_up_note: 'Overdue: Verify if customized quotation was reviewed by client.',
    archived_at: null,
    created_at: new Date(now - 4 * 86400000).toISOString(),
    updated_at: new Date(now - 3 * 86400000).toISOString(),
    owner: mockProfiles[2],
    discussions: mockDiscussions['lead-2'],
  },
  {
    id: 'lead-3',
      organization_id: 'org-venue',
    customer_name: 'Dr. Sunita Mehra',
    phone: '9871188223',
    email: 'dr.sunita@maxhealth.org',
    source: 'Google',
    event_type: 'Birthday',
    event_date_status: 'fixed',
    event_date: '2026-10-18',
    guest_count_status: 'fixed',
    guest_count: 120,
    budget: 300000,
    requirement: '50th Golden Jubilee Birthday. Intimate indoor gathering with high-tea and multi-cuisine dinner buffet.',
    owner_id: null,
    status: 'New',
    priority: 'Medium',
    next_follow_up_at: null,
    follow_up_note: null,
    archived_at: null,
    created_at: new Date(now - 2 * 3600000).toISOString(),
    updated_at: new Date(now - 2 * 3600000).toISOString(),
    owner: null,
    discussions: [],
  },
  {
    id: 'lead-4',
      organization_id: 'org-venue',
    customer_name: 'TechCorp India (Gaurav Taneja)',
    phone: '9910022334',
    email: 'events@techcorp.in',
    source: 'Website',
    event_type: 'Corporate',
    event_date_status: 'fixed',
    event_date: '2027-01-15',
    guest_count_status: 'fixed',
    guest_count: 600,
    budget: 1800000,
    requirement: 'Annual leadership summit & awards night. Need audio-visual stage setup, LED backdrop wall, and cocktail dinner.',
    owner_id: 'user-akash',
    status: 'Contacted',
    priority: 'High',
    next_follow_up_at: tomorrow11AM.toISOString(),
    follow_up_note: 'Discuss conference room layout and final GST quotation with Admin Committee.',
    archived_at: null,
    created_at: new Date(now - 24 * 3600000).toISOString(),
    updated_at: new Date(now - 6 * 3600000).toISOString(),
    owner: mockProfiles[0],
    discussions: mockDiscussions['lead-4'],
  },
  {
    id: 'lead-5',
      organization_id: 'org-venue',
    customer_name: 'Rohan & Ananya Patel',
    phone: '9899112233',
    email: 'rohan.patel@patelconstructions.com',
    source: 'Referral',
    event_type: 'Wedding',
    event_date_status: 'fixed',
    event_date: '2027-02-10',
    guest_count_status: 'fixed',
    guest_count: 500,
    budget: 2200000,
    requirement: 'Full-day Royal Wedding. Baraat reception in front lawn + Mandap in central hall + Royal dinner.',
    owner_id: 'user-rahul',
    status: 'Converted',
    priority: 'High',
    next_follow_up_at: null,
    follow_up_note: 'Advance token confirmed. Handed over to Banquet Event Operations team.',
    archived_at: null,
    created_at: new Date(now - 20 * 86400000).toISOString(),
    updated_at: new Date(now - 12 * 86400000).toISOString(),
    owner: mockProfiles[1],
    discussions: mockDiscussions['lead-5'],
  },
  {
    id: 'lead-6',
      organization_id: 'org-venue',
    customer_name: 'Suresh Bhatia',
    phone: '9818833445',
    email: 'sbhatia@bhatiatax.com',
    source: 'Walk-in',
    event_type: 'Anniversary',
    event_date_status: 'fixed',
    event_date: '2026-09-30',
    guest_count_status: 'fixed',
    guest_count: 80,
    budget: 150000,
    requirement: '25th Silver Wedding Anniversary. Preferred small banquet hall.',
    owner_id: 'user-vikram',
    status: 'Lost',
    priority: 'Low',
    next_follow_up_at: null,
    follow_up_note: 'Decided to host at home garden due to budget limits.',
    archived_at: new Date(now - 5 * 86400000).toISOString(),
    created_at: new Date(now - 15 * 86400000).toISOString(),
    updated_at: new Date(now - 5 * 86400000).toISOString(),
    owner: mockProfiles[3],
    discussions: [],
  },
  {
    id: 'lead-7',
      organization_id: 'org-venue',
    customer_name: 'Kunal Oberoi',
    phone: '9873344556',
    email: 'kunal.oberoi@oberoilogistics.com',
    source: 'Instagram',
    event_type: 'Party',
    event_date_status: 'fixed',
    event_date: '2026-11-08',
    guest_count_status: 'fixed',
    guest_count: 250,
    budget: 800000,
    requirement: 'Sangeet & Cocktail party. Required high-energy acoustics, sound limiter exemption till 11:30 PM.',
    owner_id: 'user-rahul',
    status: 'Interested',
    priority: 'Medium',
    next_follow_up_at: today6PM.toISOString(),
    follow_up_note: 'Confirm music permissions and share revised alcohol corkage menu.',
    archived_at: null,
    created_at: new Date(now - 3 * 86400000).toISOString(),
    updated_at: new Date(now - 18 * 3600000).toISOString(),
    owner: mockProfiles[1],
    discussions: mockDiscussions['lead-7'],
  },
  {
    id: 'lead-8',
      organization_id: 'org-venue',
    customer_name: 'Manish & Pooja Agarwal',
    phone: '9811456789',
    email: 'manish.agarwal@textiles.com',
    source: 'Meta',
    event_type: 'Wedding',
    event_date_status: 'fixed',
    event_date: '2026-12-18',
    guest_count_status: 'fixed',
    guest_count: 400,
    budget: 1500000,
    requirement: 'Traditional Marwari wedding ceremony. Strict pure vegetarian / Jain catering counter required.',
    owner_id: 'user-vikram',
    status: 'Follow-up',
    priority: 'High',
    next_follow_up_at: overdue1Day.toISOString(),
    follow_up_note: 'Overdue: Need to share separate Maharaj kitchen inspection dates with family.',
    archived_at: null,
    created_at: new Date(now - 5 * 86400000).toISOString(),
    updated_at: new Date(now - 2 * 86400000).toISOString(),
    owner: mockProfiles[3],
    discussions: [],
  },
];
